# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/imports/Desktop/CrazyBird.coe
read_verilog -library xil_defaultlib {
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/imports/new/Draw_Waveform.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/TestWave_Gen.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/imports/new/VGA_DISPLAY.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/imports/new/VOICE_CAPTURER.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/background_select.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/clk_cal_m.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/clk_div.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/clk_divider.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/dff_module.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_character.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_freeze_waveform.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_grid.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_grid1.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_grid_select.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_pic.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_wave_2.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_wave_3.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_wave_4.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_wave_A.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_wave_C.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_wave_D.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/draw_wave_E.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/fast_sp_module.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/grid_select.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/sram.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/vol_f.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/new/wave_color_select.v
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/imports/new/Voice_Scope_TOP.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/imports/new/CLK_108M.vhd
  C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/sources_1/imports/new/VGA_CONTROL.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/constrs_1/imports/new/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/wangh/OneDrive/Desktop/project_X.xpr/project_X5.xpr/project_XX1.xpr/project_1/project_1.srcs/constrs_1/imports/new/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Voice_Scope_TOP -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Voice_Scope_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Voice_Scope_TOP_utilization_synth.rpt -pb Voice_Scope_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
